// <auto-generated />
using BlazingPizza.EFCore.Repositories.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazingPizza.EFCore.Repositories.Migrations
{
    [DbContext(typeof(BlazinfPizzaContext))]
    partial class BlazinfPizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazingPizza.EFCore.Repositories.Entities.PizzaSpecial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 189.99m,
                            Description = "Es de queso y delicioso. Porque no querrias una?",
                            ImageUrl = "cheese.jpg",
                            Name = "Pizza clasica de queso"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 227.99m,
                            Description = "Tiene TODO tipo de tocino",
                            ImageUrl = "bacon.jpg",
                            Name = "Tocinator"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 199.50m,
                            Description = "Es la pizza con la que creciste, ¡pero ardientemente deliciosa!",
                            ImageUrl = "pepperoni.jpg",
                            Name = "Clásica de pepperoni"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 228.75m,
                            Description = "Pollo picante, salsa picante y queso azul, garantizado que entrarás en calor",
                            ImageUrl = "meaty.jpg",
                            Name = "Pollo búfalo"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 209.00m,
                            Description = "Tiene champiñones. ¿No es obvio?",
                            ImageUrl = "mushroom.jpg",
                            Name = "Amantes del champiñón"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 190.25m,
                            Description = "De piña, jamón y queso...",
                            ImageUrl = "hawaiian.jpg",
                            Name = "Hawaiana"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 218.50m,
                            Description = "Es como una ensalada, pero en una pizza",
                            ImageUrl = "salad.jpg",
                            Name = "Delicia vegetariana"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 189.99m,
                            Description = "Pizza italiana tradicional con tomates y albahaca",
                            ImageUrl = "margherita.jpg",
                            Name = "Margarita"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
